from typing import Any, Callable


def build_operator_registry(
    *,
    lightweight_index: dict[str, Any],
    kg_metadata: dict[str, Any],
    rdf_graph: Any,
    retrieve_client: Any,
    query_spec_client: Any,
    sparql_generation_client: Any,
    validate_client: Any,
    refine_client: Any,
    explain_client: Any,
    rag_model: str,
    query_spec_model: str,
    sparql_generation_model: str,
    validate_model: str,
    refine_model: str,
    explain_model: str,
    semantic_retrieve: Callable[..., dict[str, Any]],
    semantic_build_query_spec: Callable[..., dict[str, Any]],
    semantic_generate_sparql: Callable[..., dict[str, Any]],
    semantic_pre_scan_validate: Callable[..., dict[str, Any]],
    semantic_refine: Callable[..., dict[str, Any]],
    pre_programmed_scan: Callable[..., dict[str, Any]],
    semantic_explain_results: Callable[..., dict[str, Any]],
    pre_programmed_math_compute: Callable[..., dict[str, Any]],
    pre_programmed_set_intersect: Callable[..., dict[str, Any]],
    pre_programmed_union: Callable[..., dict[str, Any]],
    pre_programmed_difference: Callable[..., dict[str, Any]],
) -> dict[str, Any]:
    return {
        "_generate_model": sparql_generation_model,
        "Retrieve": lambda inputs: semantic_retrieve({**inputs, "table_index": lightweight_index}, retrieve_client, rag_model),
        "Query_Spec": lambda inputs: semantic_build_query_spec(
            {**inputs, "global_schema": inputs.get("global_schema", kg_metadata)},
            query_spec_client,
            query_spec_model,
        ),
        "Generate": lambda inputs: semantic_generate_sparql(
            {**inputs, "global_schema": kg_metadata},
            sparql_generation_client,
            sparql_generation_model,
        ),
        "Pre_Scan_Validate": lambda inputs: semantic_pre_scan_validate(inputs, validate_client, validate_model),
        "Refine": lambda inputs: semantic_refine({**inputs, "global_schema": kg_metadata}, refine_client, refine_model),
        "Scan": lambda inputs: pre_programmed_scan(inputs, rdf_graph),
        "Explain": lambda inputs: semantic_explain_results(inputs, explain_client, explain_model),
        "Math_Compute": lambda inputs: pre_programmed_math_compute(inputs),
        "Set_Intersect": lambda inputs: pre_programmed_set_intersect(inputs),
        "Set_Union": lambda inputs: pre_programmed_union(inputs),
        "Set_Difference": lambda inputs: pre_programmed_difference(inputs),
    }
