#!/usr/bin/env python3
"""Generate DAIL-SQL grading and metrics Markdown from the graded CSV."""

from __future__ import annotations

import csv
import sys
from collections import Counter, defaultdict
from pathlib import Path


FIELD_LIMIT = sys.maxsize
while True:
    try:
        csv.field_size_limit(FIELD_LIMIT)
        break
    except OverflowError:
        FIELD_LIMIT //= 10

HERE = Path(__file__).resolve().parent
BASELINES = HERE.parents[1]
RESULTS = BASELINES / "results"
GRADED = RESULTS / "dail_sql_gpt_oss_120b_domain_context_1000q_20261005_graded_gpt_5_mini.csv"
MODEL = "GPT-OSS 120B"
MODEL_ID = "openai.gpt-oss-120b-1:0"
PIPELINE = "DAIL-SQL"
GRADER = "gpt-5-mini"
INPUT_PRICE = 0.15
OUTPUT_PRICE = 0.60
SEMANTIC = ("MATCH", "MISMATCH", "PARTIAL")

CATEGORIES = [
    ("BM", "Benchmark", "wealth_management_125_question_benchmark.csv"),
    ("ARC", "At-Risk Critical", "wealth_management_at_risk_critical_125_questions.csv"),
    ("BS", "Batch Status", "wealth_management_batch_status_125_questions.csv"),
    ("EC", "Enrichment Context", "wealth_management_enrichment_context_125_questions.csv"),
    ("MC", "Multi-Step Comparative", "wealth_management_multi_step_comparative_125_questions.csv"),
    ("RC", "Reference Compliance", "wealth_management_reference_compliance_125_questions.csv"),
    ("SQ", "Scoring Quantitative", "wealth_management_scoring_quantitative_125_questions.csv"),
    ("TT", "Temporal Transaction", "wealth_management_temporal_transaction_125_questions.csv"),
]


def read_rows() -> list[dict[str, str]]:
    with GRADED.open(encoding="utf-8-sig", newline="") as handle:
        rows = list(csv.DictReader(handle))
    ids = [row.get("Sample Row ID", "") for row in rows]
    if len(rows) != 1000 or len(set(ids)) != 1000 or any(not item for item in ids):
        raise ValueError("Expected exactly 1,000 unique non-empty Sample Row IDs")
    graders = {row.get("Direct LLM Grader Model", "") for row in rows}
    if graders != {GRADER}:
        raise ValueError(f"Unexpected grader models: {sorted(graders)}")
    return rows


def statuses(rows: list[dict[str, str]]) -> Counter[str]:
    return Counter((row.get("New Status") or "").strip().upper() for row in rows)


def count_row(labels: list[str], rows: list[dict[str, str]]) -> str:
    counts = statuses(rows)
    other = len(rows) - sum(counts[status] for status in SEMANTIC)
    values = labels + [
        str(len(rows)), str(counts["MATCH"]), str(counts["MISMATCH"]),
        str(counts["PARTIAL"]), str(other),
    ]
    return "| " + " | ".join(values) + " |"


def other_text(rows: list[dict[str, str]]) -> str:
    counts = statuses(rows)
    values = [(key or "<blank>", value) for key, value in counts.items() if key not in SEMANTIC]
    return "None" if not values else ", ".join(f"`{key}`: {value}" for key, value in sorted(values))


def query_report(rows: list[dict[str, str]]) -> str:
    groups: dict[str, list[dict[str, str]]] = defaultdict(list)
    for row in rows:
        groups[(row.get("Query Type") or "<blank>").strip()].append(row)
    lines = [
        "# DAIL-SQL grading results by query type", "",
        f"All 1,000 questions were generated by `{MODEL_ID}` and graded by `{GRADER}`. "
        "`OTHER / ERROR` contains every status other than `MATCH`, `MISMATCH`, and `PARTIAL`.", "",
        "| Model | Pipeline | Total | MATCH | MISMATCH | PARTIAL | OTHER / ERROR |",
        "|---|---|---:|---:|---:|---:|---:|",
        count_row([MODEL, PIPELINE], rows), "",
        "## Query-type detail", "",
        f"Source: `{GRADED.name}`", "",
        "| Query Type | Total | MATCH | MISMATCH | PARTIAL | OTHER / ERROR |",
        "|---|---:|---:|---:|---:|---:|",
    ]
    for query_type in sorted(groups):
        lines.append(count_row([query_type], groups[query_type]))
    lines.append(count_row(["**Overall**"], rows).replace("| 1000 |", "| **1000** |", 1))
    lines.extend(["", f"Other status details: {other_text(rows)}.", ""])
    return "\n".join(lines)


def category_report(rows: list[dict[str, str]]) -> str:
    groups: dict[str, list[dict[str, str]]] = defaultdict(list)
    for row in rows:
        groups[Path(row.get("Source CSV") or "").name].append(row)
    expected = {source for _, _, source in CATEGORIES}
    if set(groups) != expected:
        raise ValueError(f"Unexpected category sources: {sorted(groups)}")
    lines = [
        "# DAIL-SQL grading results by 125-question category", "",
        "The report contains exactly 125 questions from each of the eight benchmark source categories. "
        f"All questions were graded by `{GRADER}`.", "",
        "| Code | Category | Source dataset |", "|---|---|---|",
    ]
    for code, name, source in CATEGORIES:
        lines.append(f"| {code} | {name} | `{source}` |")
    lines.extend([
        "", "## Results", "", f"Source: `{GRADED.name}`", "",
        "| Code | Category | Total | MATCH | MISMATCH | PARTIAL | OTHER / ERROR |",
        "|---|---|---:|---:|---:|---:|---:|",
    ])
    for code, name, source in CATEGORIES:
        category_rows = groups[source]
        if len(category_rows) != 125:
            raise ValueError(f"{source} has {len(category_rows)} rows instead of 125")
        lines.append(count_row([code, name], category_rows))
    lines.append(
        count_row(["**Overall**", "**All categories**"], rows).replace("| 1000 |", "| **1000** |", 1)
    )
    lines.extend(["", f"Other status details: {other_text(rows)}.", ""])
    return "\n".join(lines)


def number(value: object) -> float:
    try:
        return float(value or 0)
    except (TypeError, ValueError):
        return 0.0


def metrics_report(rows: list[dict[str, str]]) -> str:
    counts = statuses(rows)
    correct = counts["MATCH"]
    input_tokens = sum(int(number(row.get("Generation Input Tokens"))) for row in rows)
    output_tokens = sum(int(number(row.get("Generation Output Tokens"))) for row in rows)
    generation_seconds = sum(number(row.get("Generation Latency Seconds")) for row in rows)
    execution_seconds = sum(number(row.get("Elapsed Seconds")) for row in rows)
    accuracy = correct / len(rows) * 100
    token_seconds = generation_seconds / output_tokens
    token_ms = token_seconds * 1000
    input_cost = input_tokens * INPUT_PRICE / 1_000_000
    output_cost = output_tokens * OUTPUT_PRICE / 1_000_000
    total_cost = input_cost + output_cost
    average_cost = total_cost / len(rows)
    efficiency = correct / execution_seconds
    return "\n".join([
        "# DAIL-SQL baseline metrics (GPT-5 Mini grader)", "",
        f"All 1,000 questions were generated by `{MODEL_ID}` and graded by `{GRADER}`. "
        "A correct answer is a row whose final `New Status` is `MATCH`.", "",
        "DAIL-SQL makes two model calls per question. Generation tokens and time therefore include both the "
        "preliminary-SQL call and the final-SQL call.", "",
        "## Accuracy", "", "`Accuracy = MATCH answers / total questions × 100`", "",
        "| Pipeline | Questions | Correct (MATCH) | Accuracy |",
        "|---|---:|---:|---:|",
        f"| {PIPELINE} | {len(rows):,} | {correct:,} | {accuracy:.2f}% |", "",
        "## Token latency", "", "`Token latency = total generation time / total output tokens`", "",
        "| Pipeline | Input tokens | Output tokens | Generation time (s) | Seconds/output token | Milliseconds/output token |",
        "|---|---:|---:|---:|---:|---:|",
        f"| {PIPELINE} | {input_tokens:,} | {output_tokens:,} | {generation_seconds:,.3f} | {token_seconds:.6f} | {token_ms:.3f} |", "",
        "## Inference cost", "",
        "`Total cost = Σ[(input tokens × input price / 1,000,000) + (output tokens × output price / 1,000,000)]`", "",
        "`Average cost per question = total cost / 1,000`", "",
        f"Pricing assumption: Amazon Bedrock Standard on-demand `{MODEL_ID}` in `us-east-1`, at "
        f"${INPUT_PRICE:.2f} per million input tokens and ${OUTPUT_PRICE:.2f} per million output tokens. "
        "Source: [Amazon Bedrock pricing](https://aws.amazon.com/bedrock/pricing/). GPT-5 Mini grader cost is excluded.", "",
        "| Pipeline | Input cost (USD) | Output cost (USD) | Total inference cost (USD) | Average cost/question (USD) |",
        "|---|---:|---:|---:|---:|",
        f"| {PIPELINE} | ${input_cost:.6f} | ${output_cost:.6f} | ${total_cost:.6f} | ${average_cost:.9f} |", "",
        "## Execution efficiency", "",
        "`Execution efficiency = correct answers / total execution time in seconds`", "",
        "Total execution time is the sum of per-question `Elapsed Seconds`, not concurrent wall-clock duration.", "",
        "| Pipeline | Correct (MATCH) | Total execution time (s) | Execution efficiency (correct answers/s) |",
        "|---|---:|---:|---:|",
        f"| {PIPELINE} | {correct:,} | {execution_seconds:,.3f} | {efficiency:.6f} |", "",
        "## Source file", "", f"- `{GRADED.name}`", "",
    ])


def changes_report(rows: list[dict[str, str]]) -> str:
    counts = statuses(rows)
    raw_success = sum(row.get("Scan Status") == "success" for row in rows)
    raw_errors = len(rows) - raw_success
    return "\n".join([
        "# DAIL-SQL baseline implementation and run notes", "",
        "## Upstream basis", "",
        "- Repository: [BeachWang/DAIL-SQL](https://github.com/BeachWang/DAIL-SQL)",
        "- Pinned commit: `2061f68112222083134a0c9e2877961ff315ff44`",
        "- Upstream license: Apache License 2.0", "",
        "## Adaptation for this benchmark", "",
        "- Replaced the upstream target datasets with the existing 1,000-question wealth-management benchmark and SQLite database.",
        "- Replaced the upstream generation model with `openai.gpt-oss-120b-1:0`.",
        "- Used the separate validated 300-question SQL training workbook as the demonstration bank. Evaluation SQL and answers were not used as demonstrations.",
        "- Retained two-stage DAIL selection: nine masked-question examples, preliminary SQL, SQL-skeleton reselection at threshold `0.85`, and nine final examples.",
        "- Replaced Stanford CoreNLP and `all-mpnet-base-v2` with local schema-aware masking and normalized TF-IDF Euclidean distance to fit the established baseline environment.",
        "- Added `domain_intro.prompt` (SHA-256 `949546f7d36d89a79c20f39c8fc00bf7e60d15634c8f9915381aa56dd0dbeece`) and `phase0_business_rules.md` (SHA-256 `4820bfd42c2c69231669027420d10eab0cf5493e6c46193914806c5c33e072b2`) verbatim to both generation stages.",
        "- Added the output-only instruction: return only the complete SQLite query with no reasoning, explanations, Markdown, comments, or prose.",
        "- Executed generated SQL through a read-only SQLite connection and recorded tokens, generation latency, total elapsed time, selections, SQL, and raw rows.", "",
        "## Run and grading", "",
        f"- Pipeline rows: {len(rows):,}",
        f"- Successful SQL executions before grading: {raw_success:,}",
        f"- SQL execution errors before grading: {raw_errors:,}",
        "- Grading: eight parallel 125-question shards using the unchanged grader prompt and `gpt-5-mini`.",
        "- The shard merge validated 1,000 unique IDs and restored original benchmark order.", "",
        "## GPT-5 Mini results", "",
        "| MATCH | MISMATCH | PARTIAL | OTHER / ERROR | Total |",
        "|---:|---:|---:|---:|---:|",
        f"| {counts['MATCH']} | {counts['MISMATCH']} | {counts['PARTIAL']} | "
        f"{len(rows) - sum(counts[s] for s in SEMANTIC)} | {len(rows)} |", "",
        f"Other status details: {other_text(rows)}.", "",
        "## Published artifacts", "",
        "- Raw 1,000-question pipeline CSV",
        "- GPT-5 Mini graded 1,000-question CSV",
        "- Query-type grading report",
        "- Eight-category grading report",
        "- Accuracy, token-latency, inference-cost, and execution-efficiency report", "",
    ])


def main() -> None:
    rows = read_rows()
    reports = {
        "dail_sql_query_type_grading_results_gpt_5_mini.md": query_report(rows),
        "dail_sql_category_grading_results_125_each_gpt_5_mini.md": category_report(rows),
        "dail_sql_baseline_metrics_gpt_5_mini.md": metrics_report(rows),
        "dail_sql_implementation_changes_20261005.md": changes_report(rows),
    }
    for filename, content in reports.items():
        path = RESULTS / filename
        path.write_text(content, encoding="utf-8")
        print(path)


if __name__ == "__main__":
    main()
